### ISSUE TITLE
Use caching

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-datastore-flask#10]
It would be awesome to use caching to reduce our need to read the catalogs and datasets from cloud storage every time they are accessed.

https://flask-caching.readthedocs.io/en/latest/

**Comment by charlesbluca** [comment]
Looks great for our purposes - looking into it now!

**Comment by charlesbluca** [comment]
As of #14 we now have a simple cache that has a timeout of 30 minutes (i.e. pages dropped out of the cache if they aren't visited for 30 minutes).

In the future depending on usage stats we may find that it is more advantageous to use a file-based caching system or change the timeout, but for now this should work great.
