### ISSUE TITLE
Compatibility for climate.yaml

### ISSUE THREAD

**Issue by charlesbluca** [pangeo-data/pangeo-datastore-flask#17]
Now with [pangeo-datastore #75](https://github.com/pangeo-data/pangeo-datastore/pull/75) merged, there are ESM collections contained within the Pangeo master catalog. We need to create a template to provide these collections their own preview, along with some info on how to open up the datasets in Python.

**Comment by rabernat** [comment]
For this we can start with the template from the old site:

https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/docs/cmip6_glade.rst

**Comment by charlesbluca** [comment]
Working off the old template, I am hitting a hurdle when trying to render the [CSV file](https://ncar-cesm-lens.s3-us-west-2.amazonaws.com/catalogs/aws-cesm1-le.csv.gz) of 
NCAR's ESM collection - we need to alter CORS headers for this file to make it accessible to the website (and also optionally specify that it is gzip compressed, which allows PapaParse to unzip it when parsing).

cc @andersy005

**Comment by rabernat** [comment]
Let's not get hung up on that issue. I just pushed a commit to remove LENS and reference the GCS cmip6 bucket location for the cmip6 catalog. This should temporarily unblock you from the CORS problem. 

https://github.com/pangeo-data/pangeo-datastore/blob/master/intake-catalogs/climate.yaml

**Comment by charlesbluca** [comment]
This is now up and running as of #21; from here we can look into ways to reduce the memory load that is somehow being put on the app when trying to open intake-esm entries.
