### ISSUE TITLE
Url conventions

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-datastore-flask#18]
Right now we are mapping urls directly to intake paths, i.e. `https://catalog.pangeo.io/hydro/cgiar_pet`.

We might want to add a prefix to this url to give us more flexibility in the future, i.e.
`https://catalog.pangeo.io/browse/hydro/cgiar_pet`.

This could allow us to add other top-level endpoints, like `/search`, `/about`, etc.

**Comment by charlesbluca** [comment]
I agree - it shouldn't be too difficult to make a homepage for the site based on the original. I'll look into this now.

**Comment by charlesbluca** [comment]
Right now, we have a basic homepage in place - next step could be adding a table of contents, or storage usage information.
