### ISSUE TITLE
Javascript problems with xarray html_repr

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-datastore-flask#24]
This is what I see on https://catalog.pangeo.io/ocean/SOSE:

![image](https://user-images.githubusercontent.com/1197350/75182226-e23c1080-570d-11ea-89d6-b93e54c17e1d.png)

Javascript console says:

```
Refused to load the script 'https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

**Comment by charlesbluca** [comment]
This is a side effect of #23, which added some Flask-based security packages to the site but in exchange made it so the Content Security Policy needed to be overhauled. I was having some trouble managing the CSP from a local deployment of the site so I figured I would just merge the initial CSP into the site and manage it from there - thanks for pointing this out!

**Comment by charlesbluca** [comment]
I altered the CSP (located in [`main.py`](https://github.com/pangeo-data/pangeo-datastore-flask/blob/238be758458490872a05561a2670b7e0a5a785a4/main.py#L17)) to include the various fonts, stylesheets, and scripts we've been using. From now on, additional resources must be added to this policy to ensure that they are not blocked.

I'll close this issue for now, as it looks like the specific pages are now working - I'm sure that CSP is bound to cause issues in the future though!

**Comment by rabernat** [comment]
Thanks for the quick fix!
